version: '3.1'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: supysonic
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: supysonic
    volumes:
      - ./docker-entrypoint-initdb.d/enable_citext.sql:/docker-entrypoint-initdb.d/enable_citext.sql
    restart: "no"

  supysonic:
    build:
      dockerfile: supysonic.dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./PATH/TO/MUSIC:/task/music
      - ./beets_config.yaml:/root/.config/beets/config.yaml
      - beets_lib:/task/beets_lib
      - ./supysonic.conf:/etc/supysonic

    environment:
      #ADMIN_USER:
      #ADMIN_PASSWORD:
    links:
      - db:db
    depends_on:
      - db
    restart: "no"

volumes:
    beets_lib:
